application: realtor-io 
version: 2 
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js
  
- url: /widget
  static_dir: static/widget

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /s/.*
  script: handlers/service.py
  
- url: /portfolio/*
  script: handlers/portfolio.py  
  
- url: /portfolio/*.*
  script: handlers/portfolio.py 
  
- url: /portfolio
  script: handlers/portfolio.py
  
- url: /p
  script: handlers/portfolio.py
  
- url: /p/*
  script: handlers/portfolio.py

- url: .*
  script: handlers/main.py

