application: realtor-io 
version: 1 
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /s/.*
  script: handlers/service.py
  
- url: /portfolio/*
  script: handlers/portfolio.py  
  
- url: /portfolio/*.*
  script: handlers/portfolio.py  

- url: .*
  script: handlers/main.py